spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://34.70.86.164:8080/auth/realms/eureka

  # R2DBC Driver config
  r2dbc:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PWD}
    pool:
      initial-size: 10
      max-idle-time: 30m

logging:
  config: classpath:log4j2-dev-spring.xml