spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://34.70.86.164:8080/auth/realms/eureka

  # R2DBC Driver config
  r2dbc:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PWD}
    pool:
      initial-size: 10
      max-idle-time: 30m

  # GCP Cloud Storage
  gcp:
    storage:
      url-autenticada: https://storage.googleapis.com/${cloud.gcp.storage.bucket}/
      encoded-key: eyJjbGllbnRfaWQiOiAiMzI1NTU5NDA1NTkuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJjbGllbnRfc2VjcmV0IjoiWm1zc0xOakp5Mjk5OGhENENUZzJlanIyIiwicXVvdGFfcHJvamVjdF9pZCI6ICJwdXJlLWFudGhlbS0zODI2MDIiLCJyZWZyZXNoX3Rva2VuIjogIjEvLzBodGFKazlrYjVZc2pDZ1lJQVJBQUdCRVNOd0YtTDlJcmZ5NnAzR0dhdTNwYjl5Ujd6RW0zN3JpRm9TUEFEcjBPMHBxUjVtMlU5Z3dzamNtWUFBZkdQdDR5ZjVleWZPWnRLWHMiLCAgInR5cGUiOiAiYXV0aG9yaXplZF91c2VyIn0=

internal:
  services:
    eureka-clients:
      keycloak-auth:
        url: http://localhost:8090/eureka/keycloak-auth/v1
        readTimeout: 7000
        writeTimeout: 1000
        connectionTimeout: 300

logging:
  config: classpath:log4j2-dev-spring.xml